sites:
  - url: "https://yandex.ru"
    name: "yandex.ru"
    timeout: 30

  - url: "https://google.com"
    name: "google.com"
    timeout: 30

notifications:
  show_popup: true
  cnsole_output: true

general:
  check_interval: 3600
  concurrent_checks: 3
  autostart: true # Автоматический запуск программы при старте системы. По умолчанию true. NOT IMPLEMENTED